spring:
  application:
    name: artlog

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  config:
    import: optional:file:./.env[.properties]

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASS}
    url: ${DB_URL}
    hikari:
      maximum-pool-size: 10
      max-lifetime: 27000000
      idle-timeout: 60000
      connection-timeout: 30000
      validation-timeout: 5000

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        use_sql_comments: false

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:3600000}

logging:
  level:
    root: info
    com:
      artlog: info
    org:
      hibernate:
        SQL: info
        orm:
          jdbc:
            bind: info

springdoc:
  show-login-endpoint: true
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v1/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized